import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cab Insta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className="bg-white h-full">{children}</body>
    </html>
  );
}
